### ISSUE TITLE
[Feature]: Playback speed above x2

### ISSUE THREAD

**Issue by TerableCoder** [LiveTL/LiveTL#380] opened 2022-01-06 08:40 UTC
### Checklist

- [X] This is a suggestion for LiveTL, not Hyperchat. I will go to [the Hyperchat repo](https://github.com/LiveTL/HyperChat) to suggest a feature for Hyperchat.
- [X] This is a suggestion for the LiveTL web extension, not LiveTL iOS or LiveTL Android. I will go to the [iOS](https://github.com/LiveTL/ios) or [Android](https://github.com/LiveTL/android) repo to suggest features for those platforms.
- [X] I have checked for a duplicate or similar feature request/issue. I made sure to check closed issues as well.
- [X] I am not reporting a bug. If I am, I will use the bug report issue template.
- [X] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/LiveTL/LiveTL/blob/develop/CODE_OF_CONDUCT.md)

### Is your feature request related to a problem? Please describe.

In Youtube I can play videos at x3 speed with:
1- the extension "'Improve YouTube!' (Video & YouTube Tools)🎧" 
2- the extension "SpeedUp: Netflix, Prime videos"
3- the console command "document.getElementsByTagName("video")[0].playbackRate = 3"
none of these work on the LiveTL extension player.

The LiveTL video player and chat sizes are much bigger than YouTube's. So I'd like to be able to use it at x3 playback speed.

### Describe the solution you'd like

Let 1 of the above options work
or
make another way to change the playback speed

### Describe alternatives you've considered

Described above.

**Comment by ChrRubin** [comment] 2022-01-06 10:43
Those extensions don't seem to work with YT iframe players, so there's that. For example, they don't work on sites like Holodex or even on videos that are shared using the YT share as embed feature. Theoretically if you can find an extension that does that then it should work out of the box.

**Comment by TerableCoder** [comment] 2022-01-06 11:02
> Those extensions don't seem to work with YT iframe players, so there's that. For example, they don't work on sites like Holodex or even on videos that are shared using the YT share as embed feature. Theoretically if you can find an extension that does that then it should work out of the box.

I just tried "Youtube Playback Speed Control" and "Video Speed Manager" extensions.
Both of them work on Holodex, but neither works on LiveTL. I even enabled the "Allow access to file URLs" setting on "Video Speed Manager" and it still didn't work.

Do you have any suggestions?

**Comment by ChrRubin** [comment] 2022-01-06 11:31
Welp, it was worth a shot. Normally, extensions are unable to access other extensions' pages by design. I initially thought that since the player is in an iframe (which is its own page), other extensions would be able to inject into it regardless, but seems like that isn't the case.

We'd have to implement our own playback rate controls if we want to add this to LiveTL.

**Comment by r2dev2** [comment] 2022-04-08 00:44
@TerableCoder the third option works if you click the iframe with the video in it and then type in the command.

## Firefox with console editor

![iframe toggle ff console editor](https://user-images.githubusercontent.com/50760816/162340831-04caaeb7-e4e3-4445-9bcd-2f6f99ad19bb.png)

## Firefox normal console

![iframe toggle ff normal console](https://user-images.githubusercontent.com/50760816/162340906-3ad2667b-c461-4de3-9fda-9f4763a175fe.png)

## Chrome console

![iframe toggle chrome console](https://user-images.githubusercontent.com/50760816/162341102-ccf43e6f-c7df-4f98-80cd-8bd7f86a9ea3.png)

I tested out using `document.querySelector('video').playbackRate = 3;` in the console and it worked. You can use this for changing the video rate.

**Comment by KentoNishi** [comment] 2022-05-30 18:44
closing because @r2dev2's solution seems to work

**Closed as completed by KentoNishi** 2022-05-30 18:44 UTC
Labels: enhancement
