### ISSUE TITLE
Translator Mode

### ISSUE THREAD

**Issue by KentoNishi** [LiveTL/LiveTL#188] opened 2021-04-25 22:13 UTC

**Comment by Hughp135** [comment] 2021-05-28 01:16
Not sure what was intended by this, but a pretty nice feature would be to pre-fill the chat bar with the language tag after sending a message. E.g. if the translator is translating to english, automatically prefix the chat input with `[EN] ` after sending the last message. This saves a few clicks, especially if the translator is typing it in / copy pasting it from somewhere manually every time.

**Comment by Candygoblen123** [comment] 2021-05-28 01:20
This is like, the big feature of out next major release. 

> a pretty nice feature would be to pre-fill the chat bar with the language tag after sending a message

This was a thing in the old LiveTL, but never got added back. You can add it if you want.

**Comment by r2dev2** [comment] 2021-05-28 01:29
Just want to add, I'm working on a more extensive translator mode which has macros and omnicomplete.

**Comment by ChrRubin** [comment] 2021-08-02 05:48
Closing since the PR has been merged.

**Closed as completed by ChrRubin** 2021-08-02 05:48 UTC
Labels: enhancement, future
